# Generated by Django 5.1.2 on 2024-11-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_managers_remove_users_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
